package quebragalhows;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-25T23:30:40.950-03:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "QuebraGalhoWS", 
                  wsdlLocation = "http://localhost:8080/QuebraGalhoWS/services/QuebraGalhoWSPort?wsdl",
                  targetNamespace = "http://quebraGalhoWS/") 
public class QuebraGalhoWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://quebraGalhoWS/", "QuebraGalhoWS");
    public final static QName QuebraGalhoWSPort = new QName("http://quebraGalhoWS/", "QuebraGalhoWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/QuebraGalhoWS/services/QuebraGalhoWSPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QuebraGalhoWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/QuebraGalhoWS/services/QuebraGalhoWSPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QuebraGalhoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QuebraGalhoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuebraGalhoWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QuebraGalhoWS
     */
    @WebEndpoint(name = "QuebraGalhoWSPort")
    public QuebraGalhoWS getQuebraGalhoWSPort() {
        return super.getPort(QuebraGalhoWSPort, QuebraGalhoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuebraGalhoWS
     */
    @WebEndpoint(name = "QuebraGalhoWSPort")
    public QuebraGalhoWS getQuebraGalhoWSPort(WebServiceFeature... features) {
        return super.getPort(QuebraGalhoWSPort, QuebraGalhoWS.class, features);
    }

}
