
package quebragalhows;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-25T23:30:40.877-03:00
 * Generated source version: 2.7.3
 * 
 */
public final class QuebraGalhoWS_QuebraGalhoWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://quebraGalhoWS/", "QuebraGalhoWS");

    private QuebraGalhoWS_QuebraGalhoWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QuebraGalhoWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QuebraGalhoWS_Service ss = new QuebraGalhoWS_Service(wsdlURL, SERVICE_NAME);
        QuebraGalhoWS port = ss.getQuebraGalhoWSPort();  
        
       
        {
        System.out.println("Invoking buscaTodasProfissoes...");
        List<ProfissaoVO> _buscaTodasProfissoes__return = port.buscaTodasProfissoes();
        System.out.println("buscaTodasProfissoes.result=" + _buscaTodasProfissoes__return);


        }

        System.exit(0);
    }

}
